AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
  SuggestExtensions: false
  Include:
    - "**/*.rb"
    - "**/*.gemspec"
    - "Gemfile"
    - "Rakefile"

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true


Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - "lib/aim-helm-bashkit.rb"
